services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: products_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db_volume:/var/lib/mysql
  db_admin:
    depends_on:
     - db
    image: phpmyadmin:5.0
    environment:
     PMA_HOST: db
     PMA_PORT: 3306
    ports:
     - 8081:80
  cache:
    image: redis:alpine
    ports:
        - "6379:6379"
    volumes:
      - redis_volume:/data
volumes:
  db_volume:
  redis_volume: